# Basic Commands for NumPy

In [4]:
import numpy as np
x=np.zeros(3) #creating numpy arrays
x
type(x[0])

numpy.float64

In [2]:
y=np.zeros(15)
y  #different size of arrays

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
y.shape

(15,)

In [4]:
y.shape=(15,1)
y #to chance the shape of the array

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
y=np.ones(4)
y

array([1., 1., 1., 1.])

In [6]:
a=np.empty(3) 
a  #creating empty arrays

array([0., 0., 0.])

In [7]:
z=np.linspace(2,10,5) #print 5  numbers between 2 and 10  
z  #usually used for graphing purpose x axis or y axis

array([ 2.,  4.,  6.,  8., 10.])

In [7]:
z=np.array([10,20])  # array from a list of python 
z

array([10, 20])

In [9]:
l=[1,2,3,4]
q=np.array(l)
q

array([1, 2, 3, 4])

In [10]:
type(q[0])

numpy.int32

In [11]:
m=[[1,2,3],[4,5,6]]
w=np.array(m)
w

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
x=np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [22]:
ar=np.array([2,5,8,3,4])

In [23]:
np.sort(ar) #sorting

array([2, 3, 4, 5, 8])

In [31]:
br=np.array([6,7,9])
b=np.concatenate((ar,br)) #combine ar and br arrays 
b

array([2, 5, 8, 3, 4, 6, 7, 9])

In [25]:
ar.ndim #number of dimensions of array

1

In [26]:
ar.size

5

In [27]:
ar.shape

(5,)

In [14]:
c=np.array([0,1,2,3,4,5])
x=c.reshape(3,2)  #reshaping an array
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
#1d to 2d array
#to add a new axis
ar2=ar[np.newaxis, :]
ar2.shape

(1, 5)

In [41]:
#inserting new axis at a specified position 
d=np.expand_dims(ar,axis=1)
d.shape

(5, 1)

In [19]:
np.random.seed(0)
r=np.random.randint(12,size=4)
r

array([ 5,  0,  3, 11])

In [14]:
#indexing 
r[0]

5

In [20]:
r[0:3]

array([5, 0, 3])

In [16]:
r[::-1]

array([ 3, 11,  3,  0,  5])

In [17]:
print(np.sum(r))
print(np.prod(r))
print(np.mean(r))
print(np.std(r))
print(np.min(r))
print(np.max(r))
print(np.var(r))

22
0
4.4
3.6660605559646724
0
11
13.440000000000001


In [18]:
r<3

array([False,  True, False, False, False])

In [19]:
r>10

array([False, False, False,  True, False])

In [42]:
print(r[r<5])

[0 3 3]


In [43]:
print(r[r%2==0])

[0]


In [45]:
print(np.nonzero(r==3)) #another method to print elements less than 3

(array([2, 4], dtype=int64),)


In [46]:
#creating array from existing data
f=np.array([1,2,3,4,5,6,7,8,9,10])

In [47]:
#slicing 
arr=f[2:6]
arr

array([3, 4, 5, 6])

In [48]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [49]:
np.vstack((a1, a2)) #vertical stacking

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
np.hstack((a1, a2)) #horizontal stacking

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
x = np.arange(1, 25).reshape(2, 12) #combining two commands
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
np.hsplit(x, 3) #to split one array into three equal shaped arrays

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [53]:
np.hsplit(x, (3, 4)) #specific ro and column to split the arrays 

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]